Class {
	#name : 'SlangConflictingApiTestClass',
	#superclass : 'SlangClass',
	#category : 'Slang-Tests',
	#package : 'Slang-Tests'
}

{ #category : 'accessing' }
SlangConflictingApiTestClass class >> initializationOptions [

	^ nil
]

{ #category : 'accessing' }
SlangConflictingApiTestClass class >> interpreterClass [

	^ nil
]

{ #category : 'accessing' }
SlangConflictingApiTestClass class >> objectMemoryClass [

	^ nil
]

{ #category : 'accessing' }
SlangConflictingApiTestClass >> main [

	<api>
	
]

{ #category : 'accessing' }
SlangConflictingApiTestClass >> main: arg1 [

	<api>
	
]
