Class {
	#name : #VMClassIndices,
	#superclass : #VMBasicConstants,
	#classVars : [
		'ClassArrayCompactIndex',
		'ClassBitmapCompactIndex',
		'ClassBlockClosureCompactIndex',
		'ClassBlockContextCompactIndex',
		'ClassByteArrayCompactIndex',
		'ClassByteStringCompactIndex',
		'ClassFloatCompactIndex',
		'ClassFullBlockClosureCompactIndex',
		'ClassLargeNegativeIntegerCompactIndex',
		'ClassLargePositiveIntegerCompactIndex',
		'ClassMessageCompactIndex',
		'ClassMethodContextCompactIndex'
	],
	#category : #'VMMaker-Interpreter'
}
