Class {
	#name : 'VMClassIndices',
	#superclass : 'VMBasicConstants',
	#classVars : [
		'ClassArrayCompactIndex',
		'ClassBitmapCompactIndex',
		'ClassBlockClosureCompactIndex',
		'ClassBlockContextCompactIndex',
		'ClassByteArrayCompactIndex',
		'ClassByteStringCompactIndex',
		'ClassFloat32RegisterIndex',
		'ClassFloat64RegisterIndex',
		'ClassFloatCompactIndex',
		'ClassFullBlockClosureCompactIndex',
		'ClassLargeNegativeIntegerCompactIndex',
		'ClassLargePositiveIntegerCompactIndex',
		'ClassMessageCompactIndex',
		'ClassMethodContextCompactIndex'
	],
	#category : 'VMMaker-Interpreter',
	#package : 'VMMaker',
	#tag : 'Interpreter'
}
