function(find_system_LibArchive)
  find_package(LibArchive)
  if(LibArchive_FOUND)
    target_link_libraries(${VM_LIBRARY_NAME} LibArchive::LibArchive)
  else()
    message(STATUS "LibArchive not found.")
  endif()
  set(LibArchive_FOUND ${LibArchive_FOUND} PARENT_SCOPE)
endfunction()

function(download_LibArchive)
  message(STATUS "Downloading LibArchive binary")
  if(OSX)   
    add_third_party_dependency("libarchive-3.8.9")
  endif()
endfunction()

if (BUILD_BUNDLE)
  if(PHARO_DEPENDENCIES_PREFER_DOWNLOAD_BINARIES)
    download_LibArchive()
  else()
    find_system_LibArchive()

    if(NOT LibArchive_FOUND)
        download_LibArchive()
    else()
      get_target_property(LibArchive_LIBDIR LibArchive::LibArchive IMPORTED_LOCATION)
      message(STATUS "Using system LibArchive from ${LibArchive_LIBDIR}")
	  endif()
  endif()
endif()
