name: Build

on:
  push:
    branches:
      - 'pharo-8'

  workflow_dispatch:


jobs:
  build:
    name: "Build (${{matrix.os}})"
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Add MSYS2 to PATH (Windows only)
        if: matrix.os == 'windows-latest'
        run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        run: ./scripts/ci/github_build.sh

      - name: Archive artifacts
        if: matrix.os == 'ubuntu-22.04'
        uses: actions/upload-artifact@v4
        with:
          name: pharo64-linux-stable-${{ github.sha }}
          path: products/release/phcogspur64linuxht/pharo64-linux-stable.zip
          if-no-files-found: "error"